import fs from 'fs/promises';
import { SpawnRegionItem } from '@/types/serverSettings';
import { OFFICIAL_SPAWN_REGIONS } from '@/constants/serverProperties';
import { CONFIG } from '@/lib/config';
import { withLock } from '@/lib/mutex';
import { parseLuaTable } from '@/lib/sandboxUtils';

export async function readSpawnRegions(): Promise<SpawnRegionItem[]> {
  try {
    const content = await fs.readFile(CONFIG.spawnregionsPath, 'utf-8');
    
    // Attempt parsing with parseLuaTable
    // The file contains: function SpawnRegions() return { { name = "...", file = "..." }, ... } end
    // Extract everything between the return { ... }
    const returnMatch = content.match(/return\s*(\{[\s\S]*\})/);
    if (!returnMatch) {
      return OFFICIAL_SPAWN_REGIONS;
    }

    const rawTable = parseLuaTable(returnMatch[1]);
    const items: SpawnRegionItem[] = [];

    const officialNames = new Set(OFFICIAL_SPAWN_REGIONS.map((r) => r.name.toLowerCase()));

    const processEntry = (val: unknown) => {
      if (typeof val === 'object' && val !== null) {
        const obj = val as Record<string, unknown>;
        const name = typeof obj.name === 'string' ? obj.name.trim() : '';
        const file = typeof obj.file === 'string' ? obj.file.trim() : '';
        if (name && file) {
          items.push({
            name,
            file,
            isOfficial: officialNames.has(name.toLowerCase()),
          });
        }
      }
    };

    if (Array.isArray(rawTable)) {
      rawTable.forEach(processEntry);
    } else if (typeof rawTable === 'object' && rawTable !== null) {
      Object.values(rawTable).forEach(processEntry);
    }

    return items.length > 0 ? items : OFFICIAL_SPAWN_REGIONS;
  } catch {
    // If file does not exist or fails to read, return default official spawn regions
    return OFFICIAL_SPAWN_REGIONS;
  }
}

export async function saveSpawnRegions(
  regions: SpawnRegionItem[]
): Promise<{ success: boolean; error?: string }> {
  return withLock('spawnregions_file', async () => {
    try {
      const sanitize = (str: string) =>
        str
          .replace(/\\/g, '\\\\')
          .replace(/"/g, '\\"')
          .replace(/[\r\n]/g, ' ')
          .trim();

      let lua = '-- Generated by PZ-Panel\n';
      lua += 'function SpawnRegions()\n';
      lua += '    return {\n';

      for (const region of regions) {
        const cleanName = sanitize(region.name);
        const cleanFile = sanitize(region.file);
        if (cleanName && cleanFile) {
          lua += `        { name = "${cleanName}", file = "${cleanFile}" },\n`;
        }
      }

      lua += '    }\n';
      lua += 'end\n';

      // Atomic write via temporary file
      const tmpPath = `${CONFIG.spawnregionsPath}.tmp.${Date.now()}`;
      await fs.writeFile(tmpPath, lua, 'utf-8');
      await fs.rename(tmpPath, CONFIG.spawnregionsPath);

      return { success: true };
    } catch (error) {
      console.error('Failed to save spawn regions:', error);
      return { success: false, error: error instanceof Error ? error.message : String(error) };
    }
  });
}
