import { SandboxCategoryGroup } from '@/types/sandbox';

export const SANDBOX_CATEGORIES: SandboxCategoryGroup[] = [
  {
    id: 'zombies',
    name: 'Zombies & Population',
    description: 'Control zombie quantity, movement speed, horde behavior and infection transmission.',
    icon: 'Skull',
    fields: [
      {
        key: 'Zombies',
        label: 'Zombie Population Multiplier',
        description: 'Overall density of zombies in the world.',
        type: 'select',
        defaultValue: 4,
        options: [
          { value: 1, label: '1 - Insane (Maximum zombies)' },
          { value: 2, label: '2 - Very High' },
          { value: 3, label: '3 - High' },
          { value: 4, label: '4 - Normal (Default)' },
          { value: 5, label: '5 - Low' },
          { value: 6, label: '6 - None (No zombies)' },
        ],
      },
      {
        key: 'Distribution',
        label: 'Zombie Distribution',
        description: 'How zombies are placed across the map.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - Urban Focused (Concentrated in towns)' },
          { value: 2, label: '2 - Uniform (Evenly spread)' },
        ],
      },
      {
        key: 'ZombieRespawn',
        label: 'Zombie Respawn Frequency',
        description: 'How often new zombies spawn into previously cleared areas.',
        type: 'select',
        defaultValue: 4,
        options: [
          { value: 1, label: '1 - High (Constant respawning)' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - Low' },
          { value: 4, label: '4 - None (No respawning)' },
        ],
      },
      {
        key: 'Speed',
        subTable: 'ZombieLore',
        label: 'Zombie Speed',
        description: 'Movement speed of zombies.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Sprinters (Running zombies)' },
          { value: 2, label: '2 - Fast Shamblers (Normal)' },
          { value: 3, label: '3 - Shamblers (Slow)' },
          { value: 4, label: '4 - Random mix' },
        ],
      },
      {
        key: 'Strength',
        subTable: 'ZombieLore',
        label: 'Zombie Strength',
        description: 'Damage dealt by zombie attacks.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Superhuman' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - Weak' },
          { value: 4, label: '4 - Random' },
        ],
      },
      {
        key: 'Toughness',
        subTable: 'ZombieLore',
        label: 'Zombie Toughness',
        description: 'How much damage zombies can endure before dying.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Tough' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - Fragile' },
          { value: 4, label: '4 - Random' },
        ],
      },
      {
        key: 'Transmission',
        subTable: 'ZombieLore',
        label: 'Infection Transmission',
        description: 'How the Knox infection is transmitted.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - Blood + Saliva (Bites and scratches)' },
          { value: 2, label: '2 - Saliva Only (Only bites)' },
          { value: 3, label: '3 - None (Infection disabled)' },
        ],
      },
      {
        key: 'Memory',
        subTable: 'ZombieLore',
        label: 'Zombie Memory',
        description: 'How long zombies remember seeing or hearing the player.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Long' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - Short' },
          { value: 4, label: '4 - None' },
        ],
      },
    ],
  },
  {
    id: 'loot',
    name: 'Loot & Resources',
    description: 'Configure rarity of weapons, ammo, medical items, literature, and food.',
    icon: 'Package',
    fields: [
      {
        key: 'WeaponLoot',
        label: 'Melee Weapons Rarity',
        description: 'Spawn rate of melee weapons.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'RangedWeaponLoot',
        label: 'Firearms Rarity',
        description: 'Spawn rate of guns and firearms.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'AmmoLoot',
        label: 'Ammunition Rarity',
        description: 'Spawn rate of ammo boxes and magazines.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'FoodLoot',
        label: 'Fresh Food Rarity',
        description: 'Spawn rate of fresh perishable food items.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'CannedFoodLoot',
        label: 'Canned Food Rarity',
        description: 'Spawn rate of non-perishable canned food.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'MedicalLoot',
        label: 'Medical Supplies Rarity',
        description: 'Spawn rate of bandages, disinfectants, and pills.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'LiteratureLoot',
        label: 'Books & Magazines Rarity',
        description: 'Spawn rate of skill books and recipe magazines.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'LootRespawn',
        label: 'World Loot Respawn',
        description: 'How often containers respawn loot.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - None (Realistic - no respawn)' },
          { value: 2, label: '2 - Every Day' },
          { value: 3, label: '3 - Every Week' },
          { value: 4, label: '4 - Every Month' },
          { value: 5, label: '5 - Every 2 Months' },
        ],
      },
    ],
  },
  {
    id: 'world',
    name: 'World & Climate',
    description: 'Day cycle duration, utilities shutoff, helicopter events and weather.',
    icon: 'Sun',
    fields: [
      {
        key: 'DayLength',
        label: 'Day Length',
        description: 'Real-time duration of one in-game day (24 hours).',
        type: 'select',
        defaultValue: 4,
        options: [
          { value: 2, label: '30 Minutes' },
          { value: 3, label: '1 Hour' },
          { value: 4, label: '1 Hour, 30 Minutes (Default)' },
          { value: 5, label: '2 Hours' },
          { value: 7, label: '4 Hours' },
          { value: 27, label: '24 Hours (Real Time)' },
        ],
      },
      {
        key: 'WaterShut',
        label: 'Water Shutoff Schedule',
        description: 'Time range after which city water services shut off.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - 0-30 Days (Standard)' },
          { value: 2, label: '2 - 0-2 Months' },
          { value: 3, label: '3 - 0-6 Months' },
          { value: 4, label: '4 - 0-1 Year' },
          { value: 5, label: '5 - 0-5 Years' },
          { value: 6, label: '6 - Instant (Day 0)' },
          { value: 7, label: '7 - Never (Infinite water)' },
        ],
      },
      {
        key: 'ElecShut',
        label: 'Electricity Shutoff Schedule',
        description: 'Time range after which the power grid shuts off.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - 0-30 Days (Standard)' },
          { value: 2, label: '2 - 0-2 Months' },
          { value: 3, label: '3 - 0-6 Months' },
          { value: 4, label: '4 - 0-1 Year' },
          { value: 5, label: '5 - 0-5 Years' },
          { value: 6, label: '6 - Instant (Day 0)' },
          { value: 7, label: '7 - Never (Infinite power)' },
        ],
      },
      {
        key: 'Helicopter',
        label: 'Helicopter Meta-Event',
        description: 'Frequency of the military helicopter flying overhead and drawing hordes.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Never' },
          { value: 2, label: '2 - Once (First week)' },
          { value: 3, label: '3 - Sometimes (Recurring)' },
        ],
      },
      {
        key: 'Temperature',
        label: 'Global Temperature',
        description: 'Overall climate temperature modifier.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - Very Cold' },
          { value: 2, label: '2 - Cold' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Hot' },
          { value: 5, label: '5 - Very Hot' },
        ],
      },
      {
        key: 'Rain',
        label: 'Rain Frequency',
        description: 'How often rain and storms occur.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - Very Dry' },
          { value: 2, label: '2 - Dry' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Rainy' },
          { value: 5, label: '5 - Very Rainy' },
        ],
      },
    ],
  },
  {
    id: 'vehicles',
    name: 'Vehicles & Fuel',
    description: 'Vehicle spawn rates, initial condition, fuel availability and alarms.',
    icon: 'Car',
    fields: [
      {
        key: 'CarSpawnRate',
        label: 'Vehicle Spawn Density',
        description: 'Amount of cars generated along roads and parking lots.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - None' },
          { value: 2, label: '2 - Very Low' },
          { value: 3, label: '3 - Low (Default)' },
          { value: 4, label: '4 - Normal' },
          { value: 5, label: '5 - High' },
        ],
      },
      {
        key: 'ChanceHasGas',
        label: 'Gas Tank Chance',
        description: 'Probability that spawned vehicles contain fuel in their tank.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Low' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - High' },
        ],
      },
      {
        key: 'InitialGas',
        label: 'Initial Fuel Level',
        description: 'How full the fuel tank will be when gas is present.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Very Low' },
          { value: 2, label: '2 - Low' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - High' },
          { value: 5, label: '5 - Full' },
        ],
      },
      {
        key: 'CarGasConsumption',
        label: 'Fuel Consumption Rate',
        description: 'Multiplier for vehicle fuel usage per kilometer driven.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 10.0,
        step: 0.1,
      },
      {
        key: 'VehicleEasyUse',
        label: 'Easy Vehicle Access',
        description: 'If enabled, all vehicles are unlocked with full gas and keys in ignition.',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    id: 'character',
    name: 'Character & Multipliers',
    description: 'XP multiplier, starting kits, nutrition, and corpse decay speed.',
    icon: 'UserCheck',
    fields: [
      {
        key: 'XPMultiplier',
        label: 'XP Multiplier',
        description: 'Skill experience gain multiplier (e.g. 1.0 = 1x normal, 2.5 = 2.5x speed).',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 50.0,
        step: 0.1,
      },
      {
        key: 'StarterKit',
        label: 'Starter Kit',
        description: 'Spawn with a school bag, water bottle, chips, and a baseball bat.',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'Nutrition',
        label: 'Nutrition System',
        description: 'Track detailed carbohydrates, proteins, and calories influencing weight.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'HoursForCorpseRemoval',
        label: 'Hours for Corpse Removal',
        description: 'Hours in-game before dead zombie corpses decompose and disappear (0 = never).',
        type: 'number',
        defaultValue: 216.0,
        min: 0,
        max: 1000,
        step: 1,
      },
    ],
  },
];
