import { SandboxCategoryGroup } from '@/types/sandbox';

export const SANDBOX_CATEGORIES: SandboxCategoryGroup[] = [
  {
    id: 'zombies',
    name: 'Zombies & Population',
    description: 'Control zombie quantity, movement speed, horde behavior and infection transmission.',
    icon: 'Skull',
    fields: [
      {
        key: 'Zombies',
        label: 'Zombie Population Multiplier',
        description: 'Overall density of zombies in the world.',
        type: 'select',
        defaultValue: 4,
        options: [
          { value: 1, label: '1 - Insane (Maximum zombies)' },
          { value: 2, label: '2 - Very High' },
          { value: 3, label: '3 - High' },
          { value: 4, label: '4 - Normal (Default)' },
          { value: 5, label: '5 - Low' },
          { value: 6, label: '6 - None (No zombies)' },
        ],
      },
      {
        key: 'Distribution',
        label: 'Zombie Distribution',
        description: 'How zombies are placed across the map.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - Urban Focused (Concentrated in towns)' },
          { value: 2, label: '2 - Uniform (Evenly spread)' },
        ],
      },
      {
        key: 'ZombieRespawn',
        label: 'Zombie Respawn Frequency',
        description: 'How often new zombies spawn into previously cleared areas.',
        type: 'select',
        defaultValue: 4,
        options: [
          { value: 1, label: '1 - High (Constant respawning)' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - Low' },
          { value: 4, label: '4 - None (No respawning)' },
        ],
      },
      {
        key: 'Speed',
        subTable: 'ZombieLore',
        label: 'Zombie Speed',
        description: 'Movement speed of zombies.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Sprinters (Running zombies)' },
          { value: 2, label: '2 - Fast Shamblers (Normal)' },
          { value: 3, label: '3 - Shamblers (Slow)' },
          { value: 4, label: '4 - Random mix' },
        ],
      },
      {
        key: 'Strength',
        subTable: 'ZombieLore',
        label: 'Zombie Strength',
        description: 'Damage dealt by zombie attacks.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Superhuman' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - Weak' },
          { value: 4, label: '4 - Random' },
        ],
      },
      {
        key: 'Toughness',
        subTable: 'ZombieLore',
        label: 'Zombie Toughness',
        description: 'How much damage zombies can endure before dying.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Tough' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - Fragile' },
          { value: 4, label: '4 - Random' },
        ],
      },
      {
        key: 'Transmission',
        subTable: 'ZombieLore',
        label: 'Infection Transmission',
        description: 'How the Knox infection is transmitted.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - Blood + Saliva (Bites and scratches)' },
          { value: 2, label: '2 - Saliva Only (Only bites)' },
          { value: 3, label: "3 - Everyone's Infected (Reanimate upon death)" },
          { value: 4, label: '4 - None (Infection disabled)' },
        ],
      },
      {
        key: 'Mortality',
        subTable: 'ZombieLore',
        label: 'Infection Mortality Time',
        description: 'How long after contracting the Knox infection before the player dies.',
        type: 'select',
        defaultValue: 5,
        options: [
          { value: 1, label: '1 - Instant' },
          { value: 2, label: '2 - 0-30 Seconds' },
          { value: 3, label: '3 - 0-1 Minutes' },
          { value: 4, label: '4 - 0-12 Hours' },
          { value: 5, label: '5 - 2-3 Days (Default)' },
          { value: 6, label: '6 - 1-2 Weeks' },
          { value: 7, label: '7 - Never (Infection does not cause death)' },
        ],
      },
      {
        key: 'Reanimate',
        subTable: 'ZombieLore',
        label: 'Reanimation Time',
        description: 'How long after death before a corpse reanimates into a zombie.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - Instant' },
          { value: 2, label: '2 - 0-30 Seconds' },
          { value: 3, label: '3 - 0-1 Minutes (Default)' },
          { value: 4, label: '4 - 0-12 Hours' },
          { value: 5, label: '5 - 2-3 Days' },
          { value: 6, label: '6 - 1-2 Weeks' },
        ],
      },
      {
        key: 'Cognition',
        subTable: 'ZombieLore',
        label: 'Zombie Cognition & Navigation',
        description: 'Level of intelligence for navigation and door manipulation.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - Navigate & Open Doors' },
          { value: 2, label: '2 - Navigate (Smart pathfinding)' },
          { value: 3, label: '3 - Basic Navigation' },
          { value: 4, label: '4 - Random' },
        ],
      },
      {
        key: 'Memory',
        subTable: 'ZombieLore',
        label: 'Zombie Memory',
        description: 'How long zombies remember seeing or hearing the player.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Long' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - Short' },
          { value: 4, label: '4 - None' },
        ],
      },
      {
        key: 'ActiveOnly',
        subTable: 'ZombieLore',
        label: 'Zombie Activity Period',
        description: 'Whether zombies are active during day, night, or both.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - Both (Day & Night)' },
          { value: 2, label: '2 - Night Only' },
          { value: 3, label: '3 - Day Only' },
        ],
      },
    ],
  },
  {
    id: 'loot',
    name: 'Loot & Resources',
    description: 'Configure rarity of weapons, ammo, medical items, literature, and food.',
    icon: 'Package',
    fields: [
      {
        key: 'WeaponLoot',
        label: 'Melee Weapons Rarity',
        description: 'Spawn rate of melee weapons.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'RangedWeaponLoot',
        label: 'Firearms Rarity',
        description: 'Spawn rate of guns and firearms.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'AmmoLoot',
        label: 'Ammunition Rarity',
        description: 'Spawn rate of ammo boxes and magazines.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'FoodLoot',
        label: 'Fresh Food Rarity',
        description: 'Spawn rate of fresh perishable food items.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'CannedFoodLoot',
        label: 'Canned Food Rarity',
        description: 'Spawn rate of non-perishable canned food.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'MedicalLoot',
        label: 'Medical Supplies Rarity',
        description: 'Spawn rate of bandages, disinfectants, and pills.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'LiteratureLoot',
        label: 'Books & Magazines Rarity',
        description: 'Spawn rate of skill books and recipe magazines.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Extremely Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'LootRespawn',
        label: 'World Loot Respawn',
        description: 'How often containers respawn loot.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - None (Realistic - no respawn)' },
          { value: 2, label: '2 - Every Day' },
          { value: 3, label: '3 - Every Week' },
          { value: 4, label: '4 - Every Month' },
          { value: 5, label: '5 - Every 2 Months' },
        ],
      },
    ],
  },
  {
    id: 'world',
    name: 'World & Climate',
    description: 'Day cycle duration, utilities shutoff, helicopter events and weather.',
    icon: 'Sun',
    fields: [
      {
        key: 'DayLength',
        label: 'Day Length',
        description: 'Real-time duration of one in-game day (24 hours).',
        type: 'select',
        defaultValue: 4,
        options: [
          { value: 2, label: '30 Minutes' },
          { value: 3, label: '1 Hour' },
          { value: 4, label: '1 Hour, 30 Minutes (Default)' },
          { value: 5, label: '2 Hours' },
          { value: 7, label: '4 Hours' },
          { value: 27, label: '24 Hours (Real Time)' },
        ],
      },
      {
        key: 'WaterShut',
        label: 'Water Shutoff Schedule',
        description: 'Time range after which city water services shut off.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - 0-30 Days (Standard)' },
          { value: 2, label: '2 - 0-2 Months' },
          { value: 3, label: '3 - 0-6 Months' },
          { value: 4, label: '4 - 0-1 Year' },
          { value: 5, label: '5 - 0-5 Years' },
          { value: 6, label: '6 - Instant (Day 0)' },
          { value: 7, label: '7 - Never (Infinite water)' },
        ],
      },
      {
        key: 'ElecShut',
        label: 'Electricity Shutoff Schedule',
        description: 'Time range after which the power grid shuts off.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - 0-30 Days (Standard)' },
          { value: 2, label: '2 - 0-2 Months' },
          { value: 3, label: '3 - 0-6 Months' },
          { value: 4, label: '4 - 0-1 Year' },
          { value: 5, label: '5 - 0-5 Years' },
          { value: 6, label: '6 - Instant (Day 0)' },
          { value: 7, label: '7 - Never (Infinite power)' },
        ],
      },
      {
        key: 'Helicopter',
        label: 'Helicopter Meta-Event',
        description: 'Frequency of the military helicopter flying overhead and drawing hordes.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Never' },
          { value: 2, label: '2 - Once (First week)' },
          { value: 3, label: '3 - Sometimes (Recurring)' },
        ],
      },
      {
        key: 'Temperature',
        label: 'Global Temperature',
        description: 'Overall climate temperature modifier.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - Very Cold' },
          { value: 2, label: '2 - Cold' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Hot' },
          { value: 5, label: '5 - Very Hot' },
        ],
      },
      {
        key: 'Rain',
        label: 'Rain Frequency',
        description: 'How often rain and storms occur.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - Very Dry' },
          { value: 2, label: '2 - Dry' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Rainy' },
          { value: 5, label: '5 - Very Rainy' },
        ],
      },
    ],
  },
  {
    id: 'vehicles',
    name: 'Vehicles & Fuel',
    description: 'Vehicle spawn rates, initial condition, fuel availability and alarms.',
    icon: 'Car',
    fields: [
      {
        key: 'CarSpawnRate',
        label: 'Vehicle Spawn Density',
        description: 'Amount of cars generated along roads and parking lots.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - None' },
          { value: 2, label: '2 - Very Low' },
          { value: 3, label: '3 - Low (Default)' },
          { value: 4, label: '4 - Normal' },
          { value: 5, label: '5 - High' },
        ],
      },
      {
        key: 'ChanceHasGas',
        label: 'Gas Tank Chance',
        description: 'Probability that spawned vehicles contain fuel in their tank.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Low' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - High' },
        ],
      },
      {
        key: 'InitialGas',
        label: 'Initial Fuel Level',
        description: 'How full the fuel tank will be when gas is present.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Very Low' },
          { value: 2, label: '2 - Low' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - High' },
          { value: 5, label: '5 - Full' },
        ],
      },
      {
        key: 'CarGasConsumption',
        label: 'Fuel Consumption Rate',
        description: 'Multiplier for vehicle fuel usage per kilometer driven.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 10.0,
        step: 0.1,
      },
      {
        key: 'VehicleEasyUse',
        label: 'Easy Vehicle Access',
        description: 'If enabled, all vehicles are unlocked with full gas and keys in ignition.',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    id: 'character',
    name: 'Character & Multipliers',
    description: 'XP multiplier, dismantling XP cutoffs, starting kits, nutrition, and corpse decay speed.',
    icon: 'UserCheck',
    fields: [
      {
        key: 'XPMultiplier',
        label: 'Global XP Multiplier',
        description: 'Skill experience gain multiplier (e.g. 1.0 = 1x normal, 2.5 = 2.5x speed).',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 50.0,
        step: 0.1,
      },
      {
        key: 'LevelForDismantleXPCutoff',
        label: 'Maximum Dismantling XP Level',
        description: 'Maximum skill level that earns XP from dismantling objects (furniture, doors, appliances). Set to 0 to disable dismantling XP entirely (Build 42 default), or up to 10 to allow gaining XP at any level.',
        type: 'number',
        defaultValue: 0,
        min: 0,
        max: 10,
        step: 1,
      },
      {
        key: 'LevelForMediaXPCutoff',
        label: 'Maximum Media XP Level',
        description: 'Maximum skill level that earns XP from watching Life & Living TV broadcasts or VHS tapes (Default: 3, Set to 10 for max level).',
        type: 'number',
        defaultValue: 3,
        min: 0,
        max: 10,
        step: 1,
      },
      {
        key: 'StarterKit',
        label: 'Starter Kit',
        description: 'Spawn with a school bag, water bottle, chips, and a baseball bat.',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'Nutrition',
        label: 'Nutrition System',
        description: 'Track detailed carbohydrates, proteins, and calories influencing weight.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'HoursForCorpseRemoval',
        label: 'Hours for Corpse Removal',
        description: 'Hours in-game before dead zombie corpses decompose and disappear (0 = never).',
        type: 'number',
        defaultValue: 216.0,
        min: 0,
        max: 1000,
        step: 1,
      },
    ],
  },
  {
    id: 'advanced',
    name: 'Advanced & Build 42',
    description: 'Full advanced controls: Animals, Firearms mechanics, Horde peaks, Generators, Basements and Skill XP multipliers.',
    icon: 'Wrench',
    fields: [
      // Build 42 Animals
      {
        key: 'AnimalPregnancyTime',
        label: 'Animal Pregnancy Duration Multiplier',
        description: 'Time multiplier for animal gestation periods in Build 42.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 10.0,
        step: 0.1,
      },
      {
        key: 'AnimalAgeModifier',
        label: 'Animal Aging Speed Multiplier',
        description: 'Speed at which livestock grow from juvenile to adult.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 10.0,
        step: 0.1,
      },
      {
        key: 'AnimalMilkIncModifier',
        label: 'Animal Milk Production Multiplier',
        description: 'Rate of daily milk production for dairy cattle and goats.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 10.0,
        step: 0.1,
      },
      {
        key: 'AnimalWoolIncModifier',
        label: 'Animal Wool Growth Multiplier',
        description: 'Rate of wool growth for sheep in Build 42.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 10.0,
        step: 0.1,
      },
      {
        key: 'AnimalRanchChance',
        label: 'Animal Farm/Ranch Spawn Chance',
        description: 'Chance that rural barns and ranches spawn with live animals.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - None' },
          { value: 2, label: '2 - Very Low' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - High' },
        ],
      },
      {
        key: 'AnimalMetaPredator',
        label: 'Wild Predators Active',
        description: 'Simulate wild predator encounters and threat to farm livestock.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'AnimalSoundAttractZombies',
        label: 'Animal Sounds Attract Zombies',
        description: 'Animal vocalizations (moos, barks, bleats) draw nearby zombie attention.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'MaximumRatIndex',
        label: 'Maximum Rat Infestation Level',
        description: 'Upper limit for vermin and rat populations in untreated buildings.',
        type: 'number',
        defaultValue: 10,
        min: 0,
        max: 50,
        step: 1,
      },

      // Build 42 Firearms
      {
        key: 'FirearmNoiseMultiplier',
        label: 'Firearm Noise Sound Radius Multiplier',
        description: 'Radius in tiles that gunfire sound travels to attract hordes.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 5.0,
        step: 0.1,
      },
      {
        key: 'FirearmJamMultiplier',
        label: 'Firearm Jamming Probability Multiplier',
        description: 'Frequency of gun malfunctions, jams, and stovepipes based on weapon condition.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.0,
        max: 5.0,
        step: 0.1,
      },
      {
        key: 'FirearmWeatherMultiplier',
        label: 'Weather Impact on Firearms Accuracy',
        description: 'How strongly rain, fog, and wind degrade shooting accuracy.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.0,
        max: 3.0,
        step: 0.1,
      },
      {
        key: 'FirearmMoodleMultiplier',
        label: 'Moodles Impact on Firearms',
        description: 'Severity of panic, exertion, and injuries affecting weapon handling.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.0,
        max: 3.0,
        step: 0.1,
      },

      // Zombie Lore Advanced
      {
        key: 'SprinterPercentage',
        subTable: 'ZombieLore',
        label: 'Sprinter Zombie Percentage',
        description: 'Percentage (0-100%) of zombies that will run at full sprint.',
        type: 'number',
        defaultValue: 0,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        key: 'DoorOpeningPercentage',
        subTable: 'ZombieLore',
        label: 'Door Opening Zombie Percentage',
        description: 'Percentage of zombies with cognition to twist doorknobs and open doors.',
        type: 'number',
        defaultValue: 0,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        key: 'CrawlUnderVehicle',
        subTable: 'ZombieLore',
        label: 'Zombies Crawl Under Vehicles',
        description: 'Zombies can crawl underneath cars and trucks to reach players.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - Never' },
          { value: 2, label: '2 - Only Crawlers' },
          { value: 3, label: '3 - All Zombies (Default)' },
        ],
      },
      {
        key: 'Sight',
        subTable: 'ZombieLore',
        label: 'Zombie Visual Acuity',
        description: 'Visual spotting range and field of view.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Eagle Eyed (Maximum)' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - Poor' },
          { value: 4, label: '4 - Very Poor' },
          { value: 5, label: '5 - Random' },
        ],
      },
      {
        key: 'Hearing',
        subTable: 'ZombieLore',
        label: 'Zombie Hearing Range',
        description: 'Sensitivity to footsteps, whispers, and vehicle engines.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Pinpoint (Super hearing)' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - Poor' },
          { value: 4, label: '4 - Very Poor' },
          { value: 5, label: '5 - Random' },
        ],
      },
      {
        key: 'SpottedLogic',
        subTable: 'ZombieLore',
        label: 'Zombie Spotted Logic',
        description: 'Enable line of sight tracking logic for zombies pursuing survivors.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'ThumpNoChasing',
        subTable: 'ZombieLore',
        label: 'Environmental Thumping',
        description: 'Zombies attack doors and windows even when idle and not chasing players.',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'ThumpOnConstruction',
        subTable: 'ZombieLore',
        label: 'Damage Player Constructions',
        description: 'Zombies can thump and destroy player-built structures and barricades.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'TriggerHouseAlarm',
        subTable: 'ZombieLore',
        label: 'Zombies Trigger House Alarms',
        description: 'Zombies breaking windows or doors can set off burglar alarms.',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'ZombiesDragDown',
        subTable: 'ZombieLore',
        label: 'Horde Drag-Down Instant Kill',
        description: 'Multiple zombies attacking simultaneously can pull the survivor down.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'ZombiesCrawlersDragDown',
        subTable: 'ZombieLore',
        label: 'Crawler Zombies Drag-Down',
        description: 'Allow crawling zombies to participate in drag-down instant kills.',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'ZombiesFenceLunge',
        subTable: 'ZombieLore',
        label: 'Fence Lunge Attack',
        description: 'Zombies vaulting low fences will lunge forward towards feet.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'ZombiesArmorFactor',
        subTable: 'ZombieLore',
        label: 'Zombie Armor Protection Factor',
        description: 'Damage absorption modifier based on armor and heavy gear worn by zombies.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - None' },
          { value: 2, label: '2 - Low' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - High' },
        ],
      },
      {
        key: 'ZombiesMaxDefense',
        subTable: 'ZombieLore',
        label: 'Zombie Max Defense (%)',
        description: 'Maximum percentage damage reduction cap for armored zombies.',
        type: 'number',
        defaultValue: 85,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        key: 'ChanceOfAttachedWeapon',
        subTable: 'ZombieLore',
        label: 'Attached Weapons in Zombie Corpses',
        description: 'Chance of zombies spawning with axes, spears, or knives lodged in them.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - None' },
          { value: 2, label: '2 - Very Rare' },
          { value: 3, label: '3 - Rare' },
          { value: 4, label: '4 - Normal' },
          { value: 5, label: '5 - Common' },
          { value: 6, label: '6 - Abundant' },
        ],
      },
      {
        key: 'ZombiesFallDamage',
        subTable: 'ZombieLore',
        label: 'Zombie Fall Damage',
        description: 'Whether zombies suffer injury or death when falling from high places.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - Enabled (Normal fall damage)' },
          { value: 2, label: '2 - Disabled (No fall damage)' },
        ],
      },
      {
        key: 'DisableFakeDead',
        subTable: 'ZombieLore',
        label: 'Fake Dead Zombies Behavior',
        description: 'Whether corpses on the ground can pretend to be dead and suddenly attack.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - Never (Fake dead zombies appear / Default)' },
          { value: 2, label: '2 - Always (Fake dead zombies disabled)' },
          { value: 3, label: '3 - Crawlers Only' },
        ],
      },
      {
        key: 'PlayerSpawnZombieRemoval',
        subTable: 'ZombieLore',
        label: 'Clear Spawn Area Zombies',
        description: 'Removes zombies immediately surrounding player spawn points on world load.',
        type: 'select',
        defaultValue: 1,
        options: [
          { value: 1, label: '1 - Enabled (Safe spawn zone)' },
          { value: 2, label: '2 - Disabled (Zombies can spawn at start)' },
        ],
      },
      {
        key: 'FenceThumpersRequired',
        subTable: 'ZombieLore',
        label: 'Fence Thumpers Required',
        description: 'Number of zombies leaning on high fences required to tear them down.',
        type: 'number',
        defaultValue: 25,
        min: 1,
        max: 100,
        step: 1,
      },
      {
        key: 'FenceDamageMultiplier',
        subTable: 'ZombieLore',
        label: 'Fence Damage Multiplier',
        description: 'Multiplier for fence degradation rate when zombies lean or attack.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 10.0,
        step: 0.1,
      },

      // Zombie Config (Horde & Spikes)
      {
        key: 'PopulationMultiplier',
        subTable: 'ZombieConfig',
        label: 'Zombie Population Multiplier Float',
        description: 'Fine-tuned multiplier for general zombie population density.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.0,
        max: 10.0,
        step: 0.1,
      },
      {
        key: 'PopulationStartMultiplier',
        subTable: 'ZombieConfig',
        label: 'Day 1 Start Population Multiplier',
        description: 'Initial population on day 1 before ramping up to peak day.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.0,
        max: 5.0,
        step: 0.1,
      },
      {
        key: 'PopulationPeakMultiplier',
        subTable: 'ZombieConfig',
        label: 'Peak Population Multiplier',
        description: 'Target multiplier achieved when peak day arrives.',
        type: 'number',
        defaultValue: 1.5,
        min: 0.0,
        max: 10.0,
        step: 0.1,
      },
      {
        key: 'PopulationPeakDay',
        subTable: 'ZombieConfig',
        label: 'Population Peak Day',
        description: 'Day number when zombie population density reaches its maximum level.',
        type: 'number',
        defaultValue: 28,
        min: 1,
        max: 365,
        step: 1,
      },
      {
        key: 'FollowSoundDistance',
        subTable: 'ZombieConfig',
        label: 'Sound Follow Distance (Tiles)',
        description: 'Maximum distance in world tiles zombies will walk towards a heard sound.',
        type: 'number',
        defaultValue: 100,
        min: 10,
        max: 1000,
        step: 10,
      },
      {
        key: 'RallyGroupSize',
        subTable: 'ZombieConfig',
        label: 'Horde Rally Group Size',
        description: 'Average number of zombies that cluster together in wandering groups.',
        type: 'number',
        defaultValue: 20,
        min: 0,
        max: 200,
        step: 5,
      },

      // Basements & Maps
      {
        key: 'SpawnFrequency',
        subTable: 'Basement',
        label: 'Basement Spawn Frequency',
        description: 'Chance of residential and commercial buildings generating accessible basements.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - Never' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
        ],
      },
      {
        key: 'AllowMiniMap',
        subTable: 'Map',
        label: 'Allow Mini-Map UI',
        description: 'Enable in-game mini-map radar widget.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'AllowWorldMap',
        subTable: 'Map',
        label: 'Allow Full World Map (M Key)',
        description: 'Enable full isometric world map screen.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'MapAllKnown',
        subTable: 'Map',
        label: 'World Map Fully Revealed',
        description: 'Reveal full map terrain from start without fog of war.',
        type: 'boolean',
        defaultValue: false,
      },

      // Generators & Gas Infrastructure
      {
        key: 'GeneratorFuelConsumption',
        label: 'Generator Fuel Consumption Multiplier',
        description: 'Fuel usage speed for portable gasoline generators (1.0 = standard).',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 10.0,
        step: 0.1,
      },
      {
        key: 'GeneratorSpawning',
        label: 'Generator Spawn Frequency',
        description: 'Frequency of generator items spawning in garages, sheds, and stores.',
        type: 'select',
        defaultValue: 3,
        options: [
          { value: 1, label: '1 - Very Rare' },
          { value: 2, label: '2 - Rare' },
          { value: 3, label: '3 - Normal' },
          { value: 4, label: '4 - Common' },
          { value: 5, label: '5 - Abundant' },
        ],
      },
      {
        key: 'AllowExteriorGenerator',
        label: 'Exterior Generator Rain Safety',
        description: 'Allow generator operation outdoors in rain without explosive risk.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'GeneratorTileRange',
        label: 'Generator Electrical Power Radius (Tiles)',
        description: 'Horizontal tile reach of generator electrical current (default = 20).',
        type: 'number',
        defaultValue: 20,
        min: 5,
        max: 100,
        step: 1,
      },
      {
        key: 'FuelStationGasInfinite',
        label: 'Infinite Gas Station Pumps',
        description: 'Fuel pumps never run out of gasoline.',
        type: 'boolean',
        defaultValue: false,
      },

      // Environment & Injuries
      {
        key: 'FireSpread',
        label: 'Fire Spreads to Adjacent Tiles',
        description: 'Campfires, molotovs, and ovens can spread flames to surrounding structures.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'EnableSnowOnGround',
        label: 'Snow Accumulates on Ground',
        description: 'Render seasonal winter snow cover across terrain and rooftops.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'BoneFracture',
        label: 'Bone Fractures Enabled',
        description: 'High falls and vehicle collisions can break survivor arms and legs.',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'InjurySeverity',
        label: 'Injury Severity Multiplier',
        description: 'Speed and difficulty of healing cuts, scratches, and deep wounds.',
        type: 'select',
        defaultValue: 2,
        options: [
          { value: 1, label: '1 - Low' },
          { value: 2, label: '2 - Normal' },
          { value: 3, label: '3 - High' },
        ],
      },
      {
        key: 'EnablePoisoning',
        label: 'Food Poisoning Enabled',
        description: 'Eating rotten, spoiled, or toxic foods/berries causes sickness.',
        type: 'boolean',
        defaultValue: true,
      },

      // Individual Skill Multipliers
      {
        key: 'Axe',
        subTable: 'MultiplierConfig',
        label: 'Axe Skill XP Multiplier',
        description: 'XP multiplier for woodcutting and axe combat.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Aiming',
        subTable: 'MultiplierConfig',
        label: 'Aiming Skill XP Multiplier',
        description: 'XP multiplier for gun aiming and precision.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Reloading',
        subTable: 'MultiplierConfig',
        label: 'Reloading Skill XP Multiplier',
        description: 'XP multiplier for magazine loading and chambering speed.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Woodwork',
        subTable: 'MultiplierConfig',
        label: 'Carpentry Skill XP Multiplier',
        description: 'XP multiplier for barricades, furniture, and structure building.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Cooking',
        subTable: 'MultiplierConfig',
        label: 'Cooking Skill XP Multiplier',
        description: 'XP multiplier for stews, roasting, and butchering.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Farming',
        subTable: 'MultiplierConfig',
        label: 'Farming Skill XP Multiplier',
        description: 'XP multiplier for crop cultivation and disease treatment.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Mechanics',
        subTable: 'MultiplierConfig',
        label: 'Mechanics Skill XP Multiplier',
        description: 'XP multiplier for vehicle repair, engine tuning, and tire changes.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Electricity',
        subTable: 'MultiplierConfig',
        label: 'Electrical Skill XP Multiplier',
        description: 'XP multiplier for generator repair, hotwiring, and timers.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Metalwelding',
        subTable: 'MultiplierConfig',
        label: 'Metalworking Skill XP Multiplier',
        description: 'XP multiplier for welding, cutting torches, and metal barricades.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Maintenance',
        subTable: 'MultiplierConfig',
        label: 'Maintenance Skill XP Multiplier',
        description: 'XP multiplier for weapon condition preservation and durability.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Tailoring',
        subTable: 'MultiplierConfig',
        label: 'Tailoring Skill XP Multiplier',
        description: 'XP multiplier for leather patches and armor padding.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Fishing',
        subTable: 'MultiplierConfig',
        label: 'Fishing Skill XP Multiplier',
        description: 'XP multiplier for fishing with rod or spear.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Trapping',
        subTable: 'MultiplierConfig',
        label: 'Trapping Skill XP Multiplier',
        description: 'XP multiplier for catching wild game and birds with traps.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'PlantScavenging',
        subTable: 'MultiplierConfig',
        label: 'Foraging Skill XP Multiplier',
        description: 'XP multiplier for searching and finding items in the wilderness.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Doctor',
        subTable: 'MultiplierConfig',
        label: 'First Aid Skill XP Multiplier',
        description: 'XP multiplier for medical treatment, suturing, and splints.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Blacksmith',
        subTable: 'MultiplierConfig',
        label: 'Blacksmithing Skill XP Multiplier (B42)',
        description: 'XP multiplier for forging blades, tools, and metal goods.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
      {
        key: 'Husbandry',
        subTable: 'MultiplierConfig',
        label: 'Animal Husbandry Skill XP Multiplier (B42)',
        description: 'XP multiplier for caring, feeding, and breeding livestock.',
        type: 'number',
        defaultValue: 1.0,
        min: 0.1,
        max: 20.0,
        step: 0.1,
      },
    ],
  },
];
