import { PropertyMeta, SpawnRegionItem } from '@/types/serverSettings';

export const SERVER_PROPERTY_CATEGORIES = [
  { id: 'backups', label: 'Backups & Autosaves', description: 'Autosave frequency, rolling backup policies and lifecycle triggers.' },
  { id: 'performance', label: 'Performance & World', description: 'Item counts, blood decay lifespan, tick pausing and limits.' },
  { id: 'gameplay', label: 'Safety & Gameplay', description: 'PVP modifiers, safety system toggles, hit reactions and display rules.' },
  { id: 'network', label: 'Network, Access & Voice', description: 'Public listing, player slots, VOIP settings and RCON configuration.' },
] as const;

export const SERVER_PROPERTIES_SCHEMA: PropertyMeta[] = [
  // 1. Backups & Saves
  {
    key: 'SaveWorldEveryMinutes',
    label: 'Save World Frequency',
    description: 'Interval in minutes between automatic world and chunk state writes.',
    type: 'number',
    category: 'backups',
    defaultValue: 60,
    min: 1,
    max: 1440,
  },
  {
    key: 'BackupsPeriod',
    label: 'Backup Period (Minutes)',
    description: 'How often in minutes the server creates an automated backup archive (0 = disabled).',
    type: 'number',
    category: 'backups',
    defaultValue: 0,
    min: 0,
    max: 1440,
  },
  {
    key: 'BackupsCount',
    label: 'Max Retained Backups',
    description: 'Number of backup archive folders to retain before rotating older copies.',
    type: 'number',
    category: 'backups',
    defaultValue: 5,
    min: 1,
    max: 50,
  },
  {
    key: 'BackupsOnStart',
    label: 'Backup on Server Startup',
    description: 'Create a backup snapshot immediately when the server starts up.',
    type: 'boolean',
    category: 'backups',
    defaultValue: true,
  },
  {
    key: 'BackupsOnVersionChange',
    label: 'Backup on Version Change',
    description: 'Trigger a mandatory backup when the Project Zomboid build or version updates.',
    type: 'boolean',
    category: 'backups',
    defaultValue: true,
  },
  {
    key: 'AutoCreateUserInWhiteList',
    label: 'Auto-Create Whitelist Entry',
    description: 'Automatically register new connecting users into the database whitelist.',
    type: 'boolean',
    category: 'backups',
    defaultValue: false,
  },

  // 2. Performance & World
  {
    key: 'BloodSplatLifespanDays',
    label: 'Blood Splatter Lifespan (Days)',
    description: 'Days before blood stains automatically decay and despawn from world surfaces (0 = permanent).',
    type: 'number',
    category: 'performance',
    defaultValue: 0,
    min: 0,
    max: 365,
  },
  {
    key: 'PauseEmpty',
    label: 'Pause Server When Empty',
    description: 'Freeze in-game world time, erosion and zombie states when 0 players are online.',
    type: 'boolean',
    category: 'performance',
    defaultValue: true,
  },
  {
    key: 'ItemNumbersLimitPerContainer',
    label: 'Container Item Limit',
    description: 'Maximum number of items allowed in a single world container (0 = unlimited).',
    type: 'number',
    category: 'performance',
    defaultValue: 0,
    min: 0,
    max: 5000,
  },
  {
    key: 'SpeedLimit',
    label: 'Vehicle Speed Limit',
    description: 'Maximum allowable vehicle driving speed in miles per hour (MPH).',
    type: 'number',
    category: 'performance',
    defaultValue: 70,
    min: 10,
    max: 200,
  },
  {
    key: 'HoursForLootRespawn',
    label: 'Hours For Loot Respawn',
    description: 'In-game hours required for looted containers to regenerate fresh items (0 = disabled).',
    type: 'number',
    category: 'performance',
    defaultValue: 0,
    min: 0,
    max: 10000,
  },
  {
    key: 'MaxAccountsPerUser',
    label: 'Max Accounts Per User',
    description: 'Maximum distinct character save accounts allowed per player (0 = unlimited).',
    type: 'number',
    category: 'performance',
    defaultValue: 0,
    min: 0,
    max: 10,
  },

  // 3. Security & Gameplay
  {
    key: 'PVP',
    label: 'Enable Player vs Player (PVP)',
    description: 'Allow survivors to damage and kill other players.',
    type: 'boolean',
    category: 'gameplay',
    defaultValue: true,
  },
  {
    key: 'SafetySystem',
    label: 'Safety Toggle System',
    description: 'Require players to toggle off their safety skull icon before they can inflict PvP damage.',
    type: 'boolean',
    category: 'gameplay',
    defaultValue: true,
  },
  {
    key: 'PVPMeleeDamageModifier',
    label: 'PVP Melee Damage Multiplier',
    description: 'Damage multiplier for close-quarters melee weapons in PvP encounters (e.g. 30.0).',
    type: 'number',
    category: 'gameplay',
    defaultValue: 30.0,
    min: 0.1,
    max: 500.0,
  },
  {
    key: 'PVPFirearmDamageModifier',
    label: 'PVP Firearm Damage Multiplier',
    description: 'Damage multiplier for guns and firearms in PvP encounters (e.g. 50.0).',
    type: 'number',
    category: 'gameplay',
    defaultValue: 50.0,
    min: 0.1,
    max: 500.0,
  },
  {
    key: 'PVPMeleeWhileHitReaction',
    label: 'PVP Melee Hit Reaction',
    description: 'Enable flinch / stumble hit reactions during melee PvP combat.',
    type: 'boolean',
    category: 'gameplay',
    defaultValue: false,
  },
  {
    key: 'PlayerDamageFromCrash',
    label: 'Vehicle Crash Damage',
    description: 'Inflict bodily injury and trauma to passengers when colliding with obstacles or vehicles.',
    type: 'boolean',
    category: 'gameplay',
    defaultValue: true,
  },
  {
    key: 'PlayerBumpPlayer',
    label: 'Player Collision (Bumping)',
    description: 'Enable physical push/collision boxes between running players.',
    type: 'boolean',
    category: 'gameplay',
    defaultValue: false,
  },
  {
    key: 'DisplayUserName',
    label: 'Display Username Over Heads',
    description: 'Always render survivor account usernames above player characters in-game.',
    type: 'boolean',
    category: 'gameplay',
    defaultValue: true,
  },

  // 4. Network & Voice
  {
    key: 'Public',
    label: 'Public Server Listing',
    description: 'Broadcast server listing to the global public Steam server browser list.',
    type: 'boolean',
    category: 'network',
    defaultValue: false,
  },
  {
    key: 'PublicName',
    label: 'Public Server Name',
    description: 'Display title visible in the Project Zomboid multiplayer server browser.',
    type: 'string',
    category: 'network',
    defaultValue: 'My PZ Dedicated Server',
  },
  {
    key: 'PublicDescription',
    label: 'Public Description',
    description: 'Informational message and rules displayed in the server details panel.',
    type: 'string',
    category: 'network',
    defaultValue: '',
  },
  {
    key: 'MaxPlayers',
    label: 'Maximum Player Slots',
    description: 'Maximum simultaneous player connections permitted on this server.',
    type: 'number',
    category: 'network',
    defaultValue: 16,
    min: 1,
    max: 128,
  },
  {
    key: 'PingLimit',
    label: 'Max Ping Limit (ms)',
    description: 'Maximum allowable round-trip latency in ms before kick (0 = disabled).',
    type: 'number',
    category: 'network',
    defaultValue: 400,
    min: 0,
    max: 2000,
  },
  {
    key: 'VoiceEnable',
    label: 'Enable In-Game VOIP Voice',
    description: 'Activate native proximity voice chat over microphoned connections.',
    type: 'boolean',
    category: 'network',
    defaultValue: true,
  },
  {
    key: 'Voice3D',
    label: 'Directional 3D Positional Audio',
    description: 'Spatial 3D audio based on character distance and orientation.',
    type: 'boolean',
    category: 'network',
    defaultValue: true,
  },
  {
    key: 'RCONPort',
    label: 'RCON Remote Management Port',
    description: 'Listening TCP port for remote console administrative tools.',
    type: 'number',
    category: 'network',
    defaultValue: 27015,
    min: 1024,
    max: 65535,
  },
];

export const OFFICIAL_SPAWN_REGIONS: SpawnRegionItem[] = [
  { name: 'Muldraugh, KY', file: 'media/maps/Muldraugh, KY/spawnpoints.lua', isOfficial: true },
  { name: 'West Point, KY', file: 'media/maps/West Point, KY/spawnpoints.lua', isOfficial: true },
  { name: 'Rosewood, KY', file: 'media/maps/Rosewood, KY/spawnpoints.lua', isOfficial: true },
  { name: 'Riverside, KY', file: 'media/maps/Riverside, KY/spawnpoints.lua', isOfficial: true },
];
